WINDOWS_VM_NAME = "Windows 10"
KALI_VM_NAME = "kali"

VM_LIST = [
    WINDOWS_VM_NAME,
    KALI_VM_NAME
]

OBSIDIAN_PATH = r"PATH_TO_OBSIDIAN"
CHROME_PATH = r"PATH_TO_CHROME"

PROGRAM_LIST = [
    OBSIDIAN_PATH,
    CHROME_PATH
]

SPLUNK_URL = "http://localhost:8000"

VBOXMANAGE_PATH = r"PATH_TO_VBOXMANAGE"